name: github
version: 4.0.1
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: GitHub API Client Library
homepage: https://github.com/DirectMyFile/github.dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: '>=0.11.3 <0.13.0'
  http_parser: ^3.1.1
  json_annotation: ^2.0.0
dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  test: ^1.3.0
  mockito: ^3.0.0
